import { EventDispatcher, DisplayObject } from '@blakron/core';
import { PropertyEvent } from '../events/PropertyEvent.js';
import type { State } from '../states/State.js';
import type { Component } from './Component.js';

/**
 * Base class for all UI skins.
 *
 * Skins are typically generated by the EXML compiler (`@blakron/cli`).
 * A skin holds the visual children of a Component and exposes named
 * "skin parts" (e.g. `labelDisplay`, `iconDisplay`) that the host
 * component binds to via `partAdded()` / `partRemoved()`.
 *
 * The skin also owns the view-state list (`states`) and applies state
 * changes to its children when `currentState` changes.
 */
export class Skin extends EventDispatcher {
	/**
	 * Names of the skin parts exposed by this skin.
	 * Set by the EXML compiler or manually in hand-written skins.
	 */
	skinParts: string[] = [];

	// ── Size hints (influence host component measurement) ─────────────────
	width: number = NaN;
	height: number = NaN;
	minWidth: number = 0;
	maxWidth: number = 100000;
	minHeight: number = 0;
	maxHeight: number = 100000;

	/**
	 * The visual children managed by this skin.
	 * Set by the EXML compiler via `elementsContent = [...]`.
	 */
	$elementsContent: DisplayObject[] = [];

	set elementsContent(value: DisplayObject[]) {
		this.$elementsContent = value ?? [];
	}

	// ── Host component ────────────────────────────────────────────────────

	private _hostComponent: Component | null = null;

	get hostComponent(): Component | null {
		return this._hostComponent;
	}

	set hostComponent(value: Component | null) {
		if (this._hostComponent === value) return;

		if (this._hostComponent) {
			this._hostComponent.removeEventListener('addedToStage', this._onHostAddedToStage);
		}

		this._hostComponent = value;

		if (value) {
			this._commitCurrentState();
			if (!this._stateInitialized) {
				if (value.stage) {
					this._initializeStates();
				} else {
					value.once('addedToStage', this._onHostAddedToStage);
				}
			}
		}

		PropertyEvent.dispatchPropertyEvent(this, 'hostComponent');
	}

	private _onHostAddedToStage = (): void => {
		this._initializeStates();
	};

	// ── View states ───────────────────────────────────────────────────────

	/**
	 * State definitions. Set by EXML compiler or manually.
	 */
	states: State[] = [];

	private _currentState = '';
	private _stateInitialized = false;

	get currentState(): string {
		return this._currentState;
	}

	set currentState(value: string) {
		if (this._currentState === value) return;
		const old = this._currentState;
		this._currentState = value;
		this._applyState(old, value);
	}

	hasState(stateName: string): boolean {
		return this.states.some(s => s.name === stateName);
	}

	private _initializeStates(): void {
		if (this._stateInitialized) return;
		this._stateInitialized = true;
		// Apply initial state overrides
		this._applyState('', this._currentState);
	}

	private _commitCurrentState(): void {
		if (!this._stateInitialized) return;
		this._applyState('', this._currentState);
	}

	private _applyState(fromState: string, toState: string): void {
		if (!this.states || this.states.length === 0) return;

		// Remove overrides from old state
		const oldState = this.states.find(s => s.name === fromState);
		if (oldState) {
			for (const override of oldState.overrides) {
				override.remove(this._hostComponent!, this);
			}
		}

		// Apply overrides for new state
		const newState = this.states.find(s => s.name === toState);
		if (newState) {
			for (const override of newState.overrides) {
				override.apply(this._hostComponent!, this);
			}
		}
	}
}
